"""add_symbol_and_limit_columns_to_orders

Revision ID: 64aa07c97bb3
Revises: 0605fffa5c5a
Create Date: 2026-07-03 14:11:25.040588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64aa07c97bb3'
down_revision: Union[str, Sequence[str], None] = '0605fffa5c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('symbol', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('remaining_quantity', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('limit_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_stock_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'stocks', ['stock_id'], ['stock_id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['user_id'])
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'price_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_stock_id_fkey'), 'orders', 'stocks', ['stock_id'], ['stock_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'limit_price')
    op.drop_column('orders', 'remaining_quantity')
    op.drop_column('orders', 'transaction_type')
    op.drop_column('orders', 'symbol')
    # ### end Alembic commands ###
