"""create stock and portfolio tables

Revision ID: 76b4203d1444
Revises: 0b1d3de13ba5
Create Date: 2026-06-21 23:57:05.420669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b4203d1444'
down_revision: Union[str, Sequence[str], None] = '0b1d3de13ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('last_traded_price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_stocks_stock_id'), 'stocks', ['stock_id'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('portfolio',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uq_user_stock')
    )
    op.create_index(op.f('ix_portfolio_portfolio_id'), 'portfolio', ['portfolio_id'], unique=False)
    op.add_column('transactions', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['user_id'])
    op.drop_column('transactions', 'id')
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'id')
    op.add_column('wallet', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.create_index(op.f('ix_wallet_wallet_id'), 'wallet', ['wallet_id'], unique=False)
    op.drop_constraint(op.f('wallet_user_id_fkey'), 'wallet', type_='foreignkey')
    op.create_foreign_key(None, 'wallet', 'users', ['user_id'], ['user_id'])
    op.drop_column('wallet', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_user_id_fkey'), 'wallet', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_wallet_wallet_id'), table_name='wallet')
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.drop_column('wallet', 'wallet_id')
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'user_id')
    op.add_column('transactions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'transaction_id')
    op.drop_index(op.f('ix_portfolio_portfolio_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_stock_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
